[package]
name = "rust-wasm-poc"
version = "0.0.1"
authors = ["Stijn Seghers <stijnseghers@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
